server:
  port: 8061

eureka:
  server:
    wait-time-in-ms-when-sync-empty: 0
    enableSelfPreservation: false
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/