server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  level:
    org.springframework.cloud.netflix.zuul: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

zuul:
  sensitive-headers:
    - Cookie, Authorization
  routes:
    products:
      path: /products/**
      serviceId: product-service
    audit:
      path: /customer-activities/**
      serviceId: audit-service