server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  level:
    org.springframework.cloud.netflix.zuul: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

zuul:
  sensitive-headers:
    - Cookie, Authorization
  routes:
    uaa:
      path: /uaa/**
      sensitiveHeaders:
      serviceId: auth-server
    products:
      path: /products/**
      serviceId: product-service
    audit-service:
      path: /customer-activities/**
      serviceId: audit-service

#security:
#  oauth2:
#    sso:
#      loginPath: /uaa/login
#    client:
#      accessTokenUri: http://localhost:8060/uaa/oauth/token
#      userAuthorizationUri: http://localhost:8060/uaa/oauth/authorize
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: http://localhost:9999/uaa/user
#      preferTokenInfo: false
#  sessions: ALWAYS