version: "3"

services:
  product-db:
    image: postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=product-db

  mongo_db:
    image: mongo
    volumes:
      - mongo-volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    volumes:
      - redis-volume:/data
    ports:
      - 6379:6379
    restart: unless-stopped

volumes:
  postgres-volume: {}
  mongo-volume: {}
  redis-volume: {}