# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets: ['localhost:9090']

- job_name: gateway-service
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: ['gateway-service:8060']

- job_name: product-service
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: ['product-service:8100']

- job_name: audit-service
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: ['audit-service:8200']

- job_name: cart-service
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: ['cart-service:8300']

- job_name: order-service
  metrics_path: /actuator/prometheus
  static_configs:
    - targets: ['order-service:8400']
