spring:
  # spring data redis configuration
  redis:
    host: ${REDIS_HOST:localhost}
    port: 6379

okta:
  oauth2:
    issuer: https://dev-8918335.okta.com/oauth2/default
    audience: api://default
